import tkinter
screen = tkinter.Tk()
screen.geometry("350x150")
screen.title("mathematical table")
numrange = tkinter.Label(screen , text="number and range:")
usernumb = tkinter.Entry(screen)
range1 = tkinter.Radiobutton(screen , text=10)
range2 = tkinter.Radiobutton(screen , text=20)
range3 = tkinter.Radiobutton(screen , text=30)
generate = tkinter.Button(screen , text="generate")
numrange.grid(row=1, column=1)
usernumb.grid(row=1, column=2)
range1.grid(row=1, column=3)
range2.grid(row=2, column=3)
range3.grid(row=3, column=3)
generate.grid(row=4 , column=2)
screen.mainloop()